apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kiwi
  namespace: flux-system
spec:
  interval: 1m
  url: https://www.github.com/bindinc/kiwi.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: kiwi
  path: ./clusters/prod
  prune: true
  wait: true
  timeout: 5m
