<?php

declare(strict_types=1);

namespace App\Security;

final class ApiRoutePolicy
{
    public const ROUTES = [
        'api_outbox_sessions_list' => 'kiwi.read',
        'api_outbox_sessions_get' => 'kiwi.read',
        'api_outbox_sessions_action' => 'kiwi.write',
        'api_customer_editing_read' => 'kiwi.read',
        'api_customer_person_update' => 'kiwi.write',
        'api_customer_legacy_address_update' => 'kiwi.write',
        'api_customer_email_update' => 'kiwi.write',
        'api_customer_phone_update' => 'kiwi.write',
        'api_customer_mobile_update' => 'kiwi.write',
        'api_customer_bank_create' => 'kiwi.write',
        'api_customer_bank_update' => 'kiwi.write',
        'api_customer_bank_delete' => 'kiwi.write',
        'api_address_search' => 'kiwi.read',
        'api_address_validate' => 'kiwi.read',
        'api_customer_address_update' => 'kiwi.write',
        'api_address_session_close' => 'kiwi.session',
        'api_agent_status_read' => 'kiwi.session',
        'api_agent_status_update' => 'kiwi.session',
        'api_bootstrap' => 'kiwi.read',
        'api_call_queue_accept_next' => 'kiwi.write',
        'api_call_queue_clear' => 'kiwi.local.write',
        'api_call_queue_debug_generate' => 'kiwi.local.write',
        'api_call_queue_read' => 'kiwi.read',
        'api_call_queue_write' => 'kiwi.local.write',
        'api_call_session_disposition' => 'kiwi.write',
        'api_call_session_end' => 'kiwi.write',
        'api_call_session_hold' => 'kiwi.write',
        'api_call_session_identify_caller' => 'kiwi.write',
        'api_call_session_read' => 'kiwi.read',
        'api_call_session_resume' => 'kiwi.write',
        'api_call_session_start_debug' => 'kiwi.local.write',
        'api_call_session_write' => 'kiwi.local.write',
        'api_catalog_article' => 'kiwi.read',
        'api_catalog_article_order_quote' => 'kiwi.read',
        'api_catalog_articles' => 'kiwi.read',
        'api_catalog_delivery_calendar' => 'kiwi.read',
        'api_catalog_disposition_options' => 'kiwi.read',
        'api_catalog_service_numbers' => 'kiwi.read',
        'api_customer_article_orders' => 'kiwi.read',
        'api_customer_contact_history_create' => 'kiwi.write',
        'api_customer_contact_history_read' => 'kiwi.read',
        'api_customer_delivery_remarks' => 'kiwi.write',
        'api_customer_editorial_complaints' => 'kiwi.write',
        'api_customer_read' => 'kiwi.read',
        'api_customer_subscription_summaries' => 'kiwi.read',
        'api_customer_update' => 'kiwi.write',
        'api_customer_work_session_reset' => 'kiwi.session',
        'api_customers_create' => 'kiwi.write',
        'api_customers_read' => 'kiwi.read',
        'api_customers_state_read' => 'kiwi.read',
        'api_customers_state_write' => 'kiwi.local.write',
        'api_debug_reset_state' => 'kiwi.local.write',
        'api_development_feedback_screenshot' => 'signed-screenshot',
        'api_development_feedback_settings_read' => 'kiwi.session',
        'api_development_feedback_settings_update' => 'kiwi.session',
        'api_development_feedback_submit' => 'kiwi.session',
        'api_me' => 'kiwi.session',
        'api_status' => 'kiwi.session',
        'api_subscription_complaint' => 'kiwi.write',
        'api_subscription_complete_winback' => 'kiwi.write',
        'api_subscription_deceased_actions' => 'kiwi.write',
        'api_subscription_restitution_transfer' => 'kiwi.write',
        'api_subscription_update' => 'kiwi.write',
        'api_swagger_json' => 'kiwi.session',
        'api_swagger_ui' => 'kiwi.session',
        'api_webabo_offer_salescode_combinations' => 'kiwi.read',
        'api_webabo_offers' => 'kiwi.read',
        'api_workflow_article_order' => 'kiwi.write',
        'api_workflow_subscription_list' => 'kiwi.read',
        'api_workflow_subscription_queue' => 'kiwi.write',
        'api_workflow_subscription_signup' => 'kiwi.write',
        'api_workflow_subscription_status' => 'kiwi.read',
        'api_workflow_subscription_status_by_submission' => 'kiwi.read',
    ];
}
